//products
const db = {
    categories: [
        { id: 'trophies', name: 'Trophies & Cups', image: 'https://thumbs.dreamstime.com/b/sports-awards-cups-medals-competitions-prizes-awarded-champions-cup-bedal-122560743.jpg', productCount: 0 },
        { id: 'academic', name: 'Academic Plaques', image: 'https://t3.ftcdn.net/jpg/04/31/00/54/360_F_431005470_iWFmLgeRHdtxs9Xf4rzjuTxCkCeKi13H.jpg', productCount: 0 },
        { id: 'glass', name: 'Glass Mementos', image: 'https://img.freepik.com/free-vector/collection-vector-illustration-modern-glass-trophies-prizes_1441-210.jpg', productCount: 0 },
        { id: 'home-decor', name: 'Home Decor', image: 'images/35.jpeg', productCount: 0 },
        { id: 'wall-decor', name: 'Wall Decor', image: 'images/46.jpeg', productCount: 0 }
    ],
    carousels: [
        { image: 'https://content.jdmagicbox.com/comp/warangal/d6/9999px870.x870.160121121713.x5d6/catalogue/damodar-handicrafts-rangasaipet-warangal-handicraft-item-manufacturers-faxztxjhkl.jpg?imwidth=463.3333333333333', title: 'Premium Handicrafts', subtitle: 'Crafted with passion and precision' },
        { image: 'https://content.jdmagicbox.com/comp/warangal/d6/9999px870.x870.160121121713.x5d6/catalogue/damodar-handicrafts-rangasaipet-warangal-handicraft-item-manufacturers-rie9eog1g0.jpg', title: 'Corporate Awards', subtitle: 'Recognize excellence with our trophies' }
    ],
    locations: [
        { name: 'Warangal', address: 'Rangashipet Beside Mills Colony Police Station', phone: '+91 9849187918', hours: '10:00 AM - 10:00 PM' },
        { name: 'Vizag', address: 'Daba Garden Rd near Bus stop, Allipuram, Visakhapatnam', phone: '+91 9849103664', hours: '10:00 AM - 10:00 PM' },
    ],
    products: [
        // --- FIRST 19 UPDATED PRODUCTS FROM PROVIDED IMAGES ---
        { id: 1, catId: 'trophies', name: 'Blue Star Crown Trophy', price: 1250, image: 'images/1.jpeg', description: 'Premium gold-finish trophy with a striking blue star top and elegant wing-style design. Ideal for school events, sports meets, and achievement awards.' },
        { id: 2, catId: 'trophies', name: 'Royal Red Globe Cup Trophy', price: 1850, image: 'images/2.jpeg', description: 'Classic royal cup trophy featuring a red crystal globe centerpiece with decorative handles and ribbon accents. Perfect for championship and annual day awards.' },
        { id: 3, catId: 'trophies', name: 'Cricket Champion Column Trophy', price: 1450, image: 'images/3.jpeg', description: 'Elegant cricket-themed trophy with batsman figurine on top and premium pillar base. Best suited for cricket tournaments and man of the match awards.' },
        { id: 4, catId: 'trophies', name: 'Laurel Medal Victory Trophy', price: 950, image: 'images/4.jpeg', description: 'Traditional victory trophy with laurel wreath and medal plate design. Suitable for school competitions, cultural programs, and recognition ceremonies.' },
        { id: 5, catId: 'trophies', name: 'Golden Victory Hand Trophy', price: 850, image: 'images/5.jpeg', description: 'Modern artistic trophy featuring a hand holding a cup symbol. Represents success and triumph, perfect for employee recognition and competitions.' },
        { id: 6, catId: 'trophies', name: 'Royal Crown Cup Trophy', price: 1650, image: 'images/6.jpeg', description: 'Premium crown-top trophy with embossed gold cup and elegant side handles. A grand choice for champions, winners, and top performers.' },
        { id: 7, catId: 'trophies', name: 'Blue Elite Championship Cup', price: 2400, image: 'images/7.jpeg', description: 'Tall premium blue metallic championship cup with decorative golden wings and dual cup design. Ideal for prestigious tournaments and first prizes.' },
        { id: 8, catId: 'trophies', name: 'Star Honor Mini Trophy', price: 550, image: 'images/8.jpeg', description: 'Compact star-themed trophy with a sleek red base. Excellent for participation awards, classroom competitions, and small recognition events.' },
        { id: 9, catId: 'trophies', name: 'Blue Ribbon Classic Cup', price: 1150, image: 'images/9.jpeg', description: 'Elegant blue cup trophy with decorative ribbon styling and ornamental handles. Suitable for sports day, annual functions, and contests.' },
        { id: 10, catId: 'trophies', name: 'Diamond Star Excellence Trophy', price: 780, image: 'images/10.jpeg', description: 'Modern star-frame trophy with central medal slot and polished dark base. Great for excellence awards and achievement recognition.' },
        { id: 11, catId: 'trophies', name: 'Grand Gold Supreme Cup', price: 2100, image: 'images/11.jpeg', description: 'Large luxurious gold cup trophy with ribbon accents and royal lid design. Best for championship finals and prestigious award ceremonies.' },
        { id: 12, catId: 'trophies', name: 'Crystal Globe Premium Trophy', price: 1350, image: 'images/12.jpeg', description: 'Stylish premium trophy with crystal globe top and elegant black pedestal base. Perfect for corporate awards and premium presentations.' },
        { id: 13, catId: 'trophies', name: 'Silver Cricket Icon Trophy', price: 1550, image: 'images/13.jpeg', description: 'Unique silver-finish cricket trophy with batsman figurine and engraved cricket theme body. Designed for cricket leagues and school tournaments.' },
        { id: 14, catId: 'trophies', name: 'Blue Orb Pillar Trophy', price: 980, image: 'images/14.jpeg', description: 'Tall pillar-style trophy with blue orb centerpiece and ribbon decor. Perfect for cultural events, school houses, and sports competitions.' },
        { id: 15, catId: 'trophies', name: 'Classic Gold Prestige Cup', price: 1250, image: 'images/15.jpeg', description: 'Traditional gold prestige cup with elegant handles and red base. Suitable for general competitions, winners, and event honors.' },
        { id: 16, catId: 'academic', name: 'Golden Honor Cup Trophy', price: 1180, image: 'images/16.jpeg', description: 'Graceful gold-finish cup trophy with ribbon accent and premium base. A timeless choice for academic, corporate, and sports awards.' },
        { id: 17, catId: 'academic', name: 'Temple Heritage Memento', price: 3200, image: 'images/17.jpeg', description: 'Premium decorative temple-themed memento with intricate gold detailing and spacious nameplate area. Ideal for special guest honors and religious events.' },
        { id: 18, catId: 'academic', name: 'Traditional Cultural Elephant Memento', price: 3400, image: 'images/18.jpeg', description: 'Artistic elephant-shaped cultural memento with colorful heritage design and temple frame. Best for felicitations, cultural festivals, and VIP presentations.' },
        { id: 19, catId: 'academic', name: 'Silver Balaji Frame Plaque', price: 2800, image: 'images/19.jpeg', description: 'Premium wooden plaque with ornate silver frame and divine Balaji silver insert. Ideal for spiritual gifting, honors, and premium presentations.' },
        { id: 20, catId: 'academic', name: 'Telangana Heritage Event Plaque', price: 3200, image: 'images/20.jpeg', description: 'Elegant custom event plaque featuring Telangana Tourism World Heritage Day artwork with premium white and gold frame finish. Perfect for government events, conferences, and commemorative presentations.' },
        { id: 21, catId: 'academic', name: 'Golden Temple Heritage Showcase Memento', price: 3500, image: 'images/21.jpeg', description: 'Premium display-case memento with intricate golden temple arch design and velvet base. Ideal for VIP honors, heritage awards, and prestigious ceremonial gifting.' },
        { id: 22, catId: 'academic', name: 'Royal Goddess Face Decorative Plaque', price: 4200, image: 'images/22.jpeg', description: 'Luxurious decorative plaque featuring an ornate goddess face centerpiece with elegant golden floral detailing. Best suited for cultural awards, festive gifting, and premium wall display.' },
        { id: 23, catId: 'academic', name: 'Custom Reunion Honor Wooden Plaque', price: 1800, image: 'images/23.jpeg', description: 'Beautiful custom wooden plaque with personalized print panel and gold ornamental design. Perfect for school reunions, batch celebrations, and appreciation ceremonies.' },
        { id: 24, catId: 'academic', name: 'Durga Face Wooden Premium Plaque', price: 2600, image: 'images/24.jpeg', description: 'Elegant wooden plaque with embossed Durga face design and decorative corner accents. A spiritual and artistic presentation piece for honors, gifting, and decor.' },
        { id: 25, catId: 'glass', name: 'Black Edge Crystal Glass Award', price: 1500, image: 'images/25.jpeg', description: 'Modern crystal glass award with bold black side accent and slant-cut design. Ideal for corporate achievements, business recognitions, and executive honors.' },
        { id: 26, catId: 'glass', name: 'Crystal Drop Column Memento', price: 1450, image: 'images/26.jpeg', description: 'Stylish clear crystal memento with a droplet-shaped top mounted on a polished cylindrical body. Suitable for premium awards and elegant corporate presentations.' },
        { id: 27, catId: 'glass', name: 'Twisted Crystal Flame Award', price: 1650, image: 'images/27.jpeg', description: 'Contemporary twisted crystal flame-style award with artistic transparent finish. A premium choice for excellence awards, milestones, and corporate recognition.' },
        { id: 28, catId: 'glass', name: 'Annual Conference Acrylic Trophy', price: 1900, image: 'images/28.jpeg', description: 'Customized acrylic conference trophy with layered black and transparent design, perfect for annual meets, hospital conferences, and professional appreciation events.' },
        { id: 29, catId: 'glass', name: 'Crystal Diamond Top Trophy', price: 1750, image: 'images/29.jpeg', description: 'Premium crystal trophy with elegant faceted diamond top and tall transparent body. Best for top achiever awards, leadership honors, and premium corporate events.' },
        { id: 30, catId: 'glass', name: 'Blue Base Acrylic Curve Award', price: 1350, image: 'images/30.jpeg', description: 'Elegant acrylic curve award with deep blue accent base and crystal-clear upper panel. Perfect for recognition ceremonies, employee awards, and seminars.' },
        { id: 31, catId: 'glass', name: 'Red Star Acrylic Trophy', price: 1550, image: 'images/31.jpeg', description: 'Modern acrylic trophy with red star top and matching red accent base. Ideal for star performers, student awards, and competition winners.' },
        { id: 32, catId: 'home-decor', name: 'Golden Radha Krishna Statue', price: 3800, image: 'images/32.jpeg', description: 'Exquisite golden Radha Krishna decorative idol with intricate craftsmanship and divine detailing. Perfect for spiritual gifting, home decor, and festive occasions.' },
        { id: 33, catId: 'home-decor', name: 'Leaf Aura Ganesha Idol', price: 3200, image: 'images/33.jpeg', description: 'Artistic Ganesha idol set within an elegant leaf-shaped frame, finished in antique gold tones. A graceful décor piece for pooja rooms and gifting.' },
        { id: 34, catId: 'home-decor', name: 'Royal Peacock Ganesha Dome', price: 3600, image: 'images/34.jpeg', description: 'Premium Ganesha idol showcased inside a decorative dome with peacock-inspired backdrop and hanging bells. Perfect for luxury spiritual décor and festive gifting.' },
        { id: 35, catId: 'home-decor', name: 'Serene Buddha Floral Sculpture', price: 3000, image: 'images/35.jpeg', description: 'Elegant Buddha face sculpture with floral halo detailing in white and gold finish. Adds a peaceful and sophisticated touch to modern interiors.' },
        { id: 36, catId: 'home-decor', name: 'Silver Kamadhenu Cow Statue', price: 2500, image: 'images/36.jpeg', description: 'Decorative silver-finish Kamadhenu cow and calf figurine with intricate engraved patterns. Ideal for vastu, spiritual gifting, and premium shelf décor.' },
        { id: 37, catId: 'home-decor', name: 'Golden Elephant Wall Accent', price: 3400, image: 'images/37.jpeg', description: 'Stylish elephant-head wall décor in antique gold finish with artistic ear detailing. A bold statement piece for hallways, living rooms, and office walls.' },
        { id: 38, catId: 'home-decor', name: 'White Gold Ganesha Idol', price: 4200, image: 'images/38.jpeg', description: 'Luxurious white and gold Ganesha idol embellished with gemstone accents and mounted on a premium black base. Perfect for festive gifting and pooja décor.' },
        { id: 39, catId: 'home-decor', name: 'Royal Horse Head Sculpture', price: 3100, image: 'images/39.jpeg', description: 'Contemporary horse head sculpture in silver finish with flowing golden mane. A premium décor accent symbolizing strength, grace, and success.' },
        { id: 40, catId: 'wall-decor', name: 'Copper Shiva Wall Plaque', price: 3500, image: 'images/40.jpeg', description: 'Detailed copper-finish Shiva wall plaque with ornate frame and meditative pose. Ideal for sacred spaces, yoga rooms, and premium gifting.' },
        { id: 41, catId: 'trophies', name: 'Blue Phoenix Wings Sculpture', price: 2900, image: 'images/41.jpeg', description: 'Modern artistic wing sculpture in striking blue and gold finish mounted on a sturdy black base. A symbol of ambition and freedom for offices and homes.' },
        { id: 42, catId: 'wall-decor', name: 'Autumn Leaf Metal Wall Art', price: 3800, image: 'images/42.jpeg', description: 'Textured wall art panel featuring elegant metallic autumn leaves over abstract circular patterns. A sophisticated centerpiece for modern living spaces.' },
        { id: 43, catId: 'home-decor', name: 'Moonlight Ganesha Shadow Frame', price: 3300, image: 'images/43.jpeg', description: 'Creative framed artwork of playful Ganesha seated on a crescent moon with hanging bells. A charming decorative piece for bedrooms and pooja corners.' },
        { id: 44, catId: 'home-decor', name: 'Bronze Ganesha Blessing Idol', price: 3900, image: 'images/44.jpeg', description: 'Rich bronze-finish Ganesha idol with intricate carvings and blessing posture. A timeless spiritual décor piece for homes, offices, and gifting.' },
        { id: 45, catId: 'wall-decor', name: 'Flame Feather Art Frame', price: 4100, image: 'images/45.jpeg', description: 'Premium framed artwork featuring a luminous feather design with fiery multicolor detailing on a deep black background. Ideal for luxury wall décor.' },
        { id: 46, catId: 'wall-decor', name: 'Vintage Crossed Swords Shield', price: 4500, image: 'images/46.jpeg', description: 'Classic wall-mounted shield décor with crossed vintage swords in antique copper finish. A bold heritage-inspired statement for offices, lounges, and study rooms.' }
    ]
};

// Automatically update category counts
db.categories.forEach(cat => {
    cat.productCount = db.products.filter(p => p.catId === cat.id).length;
});
